### ISSUE TITLE
4x4 matrix gets ValueError occasionally 

### ISSUE THREAD

**Issue by CFZeon** [QuantuMope/handeye-4dof#1]
Hello!

I was using the handeye calibration algorithm and I found this problem where certain values are not valid even though they are all valid 4x4 matrices. Here is what the error looks like:
![image](https://user-images.githubusercontent.com/61812576/141395714-e75c23dc-1bcc-4c3f-ac5b-a18fa438bec9.png)
I have been working around this by commenting out the problematic sample data but this reduces my sample size significantly.

Regards,
Zeon

**Comment by CFZeon** [comment]
Just to add on: This is the last axis and angle that I got right before the angle occurred which looks correct as far as I'm concerned.

![image](https://user-images.githubusercontent.com/61812576/141397113-2abccfc3-8243-4edd-bb94-cf596ab71546.png)

Edit:
I believe it stems from the if-clause here not returning 2 values 
![image](https://user-images.githubusercontent.com/61812576/141397410-3bba154d-4eb2-49f1-958f-4aa2f176d06b.png)

Regards,
Zeon

**Comment by QuantuMope** [comment]
Thanks for finding this bug. The latest [commit](https://github.com/QuantuMope/handeye-4dof/commit/edeff2d7ed55425648baf47dcb979600a46375f5) should take care of the issue.

Could you update whether or not your calibration results are plausible?
I only had one set of data to test with and so there may be other bugs I'm unaware of.

**Comment by CFZeon** [comment]
Hello,

The calibration results are plausible (In my case it varies by centimeters) but I often hit the singularity check with the values I obtain with my robot. 

I am not too sure of what conditions would pass the singularity check but my sample sizes are very small with high degree of error which is why I think that a few centimeters of variance is acceptable. 

Regards,
Zeon

**Comment by sim-lab-dev** [comment]
Hi,
@CFZeon , I meet the same problem that  hit the singularity check with the values, did you solve the problem

**Comment by QuantuMope** [comment]
Hi @RXWein, hitting the singularity check indicates that you are not providing transforms with enough "exploration" in the 4D space. In other words, your sampled data may reduce to 3DOFs or less. Does your sampled data fully explore (x, y, z, theta) enough? Increasing your sample size and accuracy of measurements will also help greatly.
