### ISSUE TITLE
Is this repo only applicable to general (non-SCARPA) 4 DOF Robots

### ISSUE THREAD

**Issue by mostafarohani** [QuantuMope/handeye-4dof#3]
I am looking to expand on this repo for the  board-on-hand use case. But even initially I am confused how the paper cited reduces the search space for the board-to-hand transform. 

If you look at closed sourcing tooling like for rc-visard: https://doc.rc-visard.com/latest/en/handeye_calibration.html

they ask the user to provide 2 of the 6 parameters in the transform ("the TCP rotation axis and the offset from the TCP to the visible surface of the grid along the TCP rotation axis must be provided.") to make up for the fact that robot can only provided measurements along a 4 DOF subspace. This makes sense to me. But in this repo the user provides no such input? Is there some baked in assumption of the positioning of the camera/board-on-hand?

**Comment by QuantuMope** [comment]
This repo should work with any robot manipulator possessing 4 DOFs (which includes SCARA robots).

The cited paper deals with measurements from a 4DOF subspace by expressing motions as screws. What this exactly means is best expressed by the paper itself. Note that the produced rigid transform is still not perfect as it only provides 5 of 6 DOFs.

It seems that the link you provided is for proprietary software and therefore, I do not know what type of calibration algorithm they are using. From their requirements though, it seems that the algorithm they use is different from the one implemented in this repo. If you wish to contribute to this repo for the eye-on-base case, please do so using the same dual quaternion calibration algorithm from the cited paper.

Will close this issue for now. Let me know if you have any more questions.
